name: model-bank-note-auth
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python model.py
          
          echo "## MODEL METRICS" > report.md
          cat static/metrics.txt >> report.md
          
          echo "## Data Viz" >> report.md
          cml-publish static/feature_importance.png --md >> report.md
          cml-publish static/confmat.png --md >> report.md
          cml-send-comment report.md
